config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'
  get '/about', to: 'pages#about'
  get '/list_users', to: 'pages#list_users'

  get '/pages/edit_avatar', to: 'pages#edit_avatar'
  patch '/pages/update_avatar', to: 'pages#update_avatar'
  devise_for :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    # can :manage, Post, :user => :id

    if user.has_role? :superuser
      can :manage, :all
    elsif user.has_role? :blogger
      can :read, Post
      can :create, Post
      can :manage, Post, Post do |post|
        post.user_id == user.id
      end
    else
      can :read, Post
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 5 }
  validates :body,  presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "default.jpg"
  validates_attachment_content_type :avatar, content_type: %r{ /\Aimage\/.*\Z/ }
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :set_default_role

  def set_default_role
    add_role :blogger
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { render nothing: true, status: :forbidden }
      format.html { redirect_to main_app.post_url, :alert => exception.message }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def list_users
    @users = User.all
  end

  def edit_avatar
  end

  def update_avatar
    @user = User.find(current_user.id)
    @user.update_attribute(:avatar, params[:user][:avatar]) unless (params[:user]).nil?
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
    # authorize! :edit, @post, :message => "Unable to manage this post. You are not author."
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    # authorize! :edit, @post, :message => "Unable to manage this post. You are not author."
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="sidebar">
		<div id="logo">
			<%= link_to root_path do %>
				<%= image_tag("logo.svg", size: "33x33")%>
			<% end %>
		</div>

		<ul>
			<li class="category">Website</li>
			<li><%= link_to "Blog", root_path %></li>
			<li><%= link_to "About", about_path %></li>
		</ul>

		<ul>
			<li class="category">Social</li>
			<li><a href="https://github.com/cypo721">Github</a></li>
		</ul>
    	<% if !user_signed_in? %>
			  <p class="sign_in"><%= link_to "Login", new_user_session_path %></p> <br>
        <p class="sign_up"><%= link_to "Sing up", new_user_registration_path %></p>
      <% else %>
        <p class="avatar"> <%= link_to "/pages/edit_avatar" do %> <%= image_tag current_user.avatar, :class => "as" %> <% end %> </p>
        <p class="sign_in">Logged as <%= current_user.email %></p>
      <% end %>
	</div>

	<div id="main_content">
		<div id="header">
      <% if current_page?(root_path) %>
				<p>All Posts</p>
			<% elsif current_page?(about_path) %>
				<p>About</p>
			<% else %>
				<%= link_to "Back to All Posts", root_path %>
			<% end %>

			<% if user_signed_in? %>
				<div class="buttons">
          <% if current_user.has_role? :superuser %>
          <a class="button" href="/list_users">List of users</a>
          <% end %>
					<a class="button" href="/posts/new">New post</a>
					<a class="button" data-method="delete" href="/users/sign_out">Log out</a>
				</div>
      <% end %>
		</div>

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>

		<%= yield %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">

	</div>

	<div id="content">
		<h1>Hey, I'm Patrik Cyprian</h1>
		<p>This is my homework for Ruby lessons.</p>
	</div>
</div>

app/views/pages/edit_avatar.html.erb
<h2> Update profile avatar </h2>
<div>
  <br>
  <%= form_for current_user  ,url: "update_avatar", html: { multipart: true } do |form| %>
  <%= form.file_field :avatar %>
  <%= form.submit %>
<% end %>
</div

app/views/pages/list_users.html.erb
<% @users.each do |user| %>
	<div class="post_wrapper">
		<h2 class="title"><%= user.email %></h2>
		<p class="date"> Registered:  <%= user.created_at.strftime("%B %d, %Y") %></p>
	</div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_area :body %><br>
	<br>
	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>

	<%= render 'form' %>
	</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to post.title, post %></h2>
		<p> Autor : <%= User.find(post.user_id).email.split('@').first %> </p>
		<p class="date"> <%= post.created_at.strftime("%B %d, %Y") %></p>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title"><%= @post.title %></h1>
	<p class="date">
		Autor : <%= User.find(@post.user_id).email.split('@').first %> <br>
		Submitted <%= time_ago_in_words(@post.created_at) %> Ago
		<%-# if (user_signed_in? && current_user.has_role?(:superuser)) %>
		| <%= link_to 'Edit', edit_post_path(@post), :class=>"button" %> |
		  <%= link_to 'Delete', @post, :class=>"button", method: :delete, data: { confirm: 'Are you sure?' } %>
	  <%-# end %>
	</p>
	<p class="body" > <%= @post.body %></p>

</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>